////
POST http://localhost:5000/api/phones HTTP/1.1
Content-Type: application/json

{
  "model": "samsung",
  "brandId": 1,
  "year": "2021-09-22",
  "ram": 6,
  "cpu": "A15 Bionic",
  "displaySize": 6,
  "hasNFC": true
}



######

GET http://localhost:5000/api/phones HTTP/1.1


#####
GET http://localhost:5000/api/phones/filters?page=1&limit=5 HTTP/1.1

####
GET http://localhost:5000/api/phones/filters?limit=3&model=samsung&year=2021 HTTP/1.1

###
GET http://localhost:5000/api/phones/filters?year=2021 HTTP/1.1


###
PUT http://localhost:5000/api/phones/1 HTTP/1.
Content-Type: application/json

{
  "ram": 8
}

###
DELETE  http://localhost:5000/api/phones/7 HTTP/1.







###
GET http://localhost:5000/api/phones/brands/Apple HTTP/1.1


###
POST http://localhost:5000/api/phones/brands/Apple HTTP/1.1
Content-Type: application/json

{
  "model": "Iphone 15",
  "year": "2021-09-22",
  "ram": 6,
  "cpu": "A15 Bionic",
  "displaySize": 6,
  "hasNFC": true
}